In [1]:
import tensorflow as tf
tf.__version__

'2.0.0-beta0'

In [14]:
import numpy as np

In [2]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6, 7])

In [7]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [5]:
for ele in dataset:
    print(ele.numpy())

1
2
3
4
5
6
7


In [6]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2], [3, 4], [5, 6]])

In [8]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [9]:
dataset_dict = tf.data.Dataset.from_tensor_slices({
    'a': [1, 2, 3, 4],
    'b': [6, 7, 8, 9],
    'c': [12, 13, 14, 15]
})

In [10]:
dataset_dict

<TensorSliceDataset shapes: {a: (), b: (), c: ()}, types: {a: tf.int32, b: tf.int32, c: tf.int32}>

In [13]:
for e in dataset_dict:
    print(e)

{'a': <tf.Tensor: id=60, shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: id=61, shape=(), dtype=int32, numpy=6>, 'c': <tf.Tensor: id=62, shape=(), dtype=int32, numpy=12>}
{'a': <tf.Tensor: id=66, shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: id=67, shape=(), dtype=int32, numpy=7>, 'c': <tf.Tensor: id=68, shape=(), dtype=int32, numpy=13>}
{'a': <tf.Tensor: id=72, shape=(), dtype=int32, numpy=3>, 'b': <tf.Tensor: id=73, shape=(), dtype=int32, numpy=8>, 'c': <tf.Tensor: id=74, shape=(), dtype=int32, numpy=14>}
{'a': <tf.Tensor: id=78, shape=(), dtype=int32, numpy=4>, 'b': <tf.Tensor: id=79, shape=(), dtype=int32, numpy=9>, 'c': <tf.Tensor: id=80, shape=(), dtype=int32, numpy=15>}


In [19]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6, 7])
dataset = dataset.shuffle(7)
dataset = dataset.repeat(3)
dataset = dataset.batch(3)

In [20]:
for ele in dataset:
    print(ele.numpy())

[6 5 7]
[2 1 3]
[4 4 7]
[2 3 5]
[6 1 4]
[6 3 7]
[1 5 2]


In [21]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6, 7]))

In [22]:
dataset = dataset.map(tf.square)

In [23]:
for ele in dataset:
    print(ele.numpy())

1
4
9
16
25
36
49
